
on:
  push:

name: Build preview package

jobs:
  deb-package:
    name: build DEB-Package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install debhelper build-essential -y

      - name: Build
        run: make deb

      - name: Copy artifacts
        run: mkdir package && cp ../linuxmuster-linuxclient7_* ./package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: deb-package
          path: package/*
