
on:
  push:

name: Build preview package

jobs:
  deb-package:
    name: build DEB-Package
    runs-on: ubuntu-24.04
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install debhelper build-essential -y

      - name: Build
        run: make deb

      - name: Copy artifacts
        run: mkdir package && cp ../linuxmuster-linuxclient7_* ./package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: package/*
