name: Push to GitHub archive repo

on:
  workflow_dispatch

jobs:
  publish_latest_release_to_package_server:
    name: Push latest release to GitHub archive repo
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.REPO_SSH_KEY }}"
          
      - name: Clone archive repo
        uses: actions/checkout@v2
        with: 
          repository: "linuxmuster/archive"
          ssh-key: ${{ secrets.REPO_SSH_KEY }}
          path: "./archive"
          
      - name: Prepare download
        run: mkdir "packages"
          
      - name: Download assets from latest release
        uses: Itsblue/download-release-assets-action@v4
        with:
          file: ".*"
          path: "./packages"
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Prepare environment
        run: |
          export PACKAGE=$(grep -i ^Source packages/*.changes | awk -F\: '{ print $2 }' | awk '{ print $1 }')
          echo "::set-env name=PACKAGE::$PACKAGE"
          
          export DISTRIBUTION=$(grep -i ^Distribution packages/*.changes | awk -F\: '{ print $2 }' | awk '{ print $1 }')
          echo "::set-env name=DISTRIBUTION::$DISTRIBUTION"
          
          export VERSION=$(grep -i ^Version packages/*.changes | awk -F\: '{ print $2 }' | awk '{ print $1 }')
          echo "::set-env name=VERSION::$VERSION"
          
      - name: Copy packages
        run: |
          mkdir -p archive/packages/$PACKAGE/$DISTRIBUTION
          rm -rf archive/packages/$PACKAGE/$DISTRIBUTION/*
          
          cp packages/* archive/packages/$PACKAGE/$DISTRIBUTION
          
      - name: Push to repo
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          cd archive
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update/$PACKAGE-$DISTRIBUTION-$VERSION
          git add *
          git commit -a -m "Update $PACKAGE/$DISTRIBUTION to $VERSION (By GitHub actions)"
          git push --set-upstream origin update/$PACKAGE-$DISTRIBUTION-$VERSION
